In [3]:
import cv2
import torch
from transformers import ViTImageProcessor, ViTForImageClassification

# Initialize the image processor and model
processor = ViTImageProcessor.from_pretrained('google/vit-base-patch16-224-in21k')
model = ViTForImageClassification.from_pretrained('ChrisGuarino/model')  # Replace with your model
model.eval()

# Define your class labels
class_labels = ['Prim', 'Rupe', 'No Cat']  # Replace with your actual labels

# Start the webcam
cap = cv2.VideoCapture(0)

#Confidence Threshold
confidence_threshold = .8  # Define a threshold

while True:
    ret, current_frame = cap.read()

    if ret:
        # Preprocess the frame
        frame_resized = cv2.resize(current_frame, (640, 480))
        frame_rgb = cv2.cvtColor(frame_resized, cv2.COLOR_BGR2RGB)
        inputs = processor(images=frame_rgb, return_tensors="pt")

        # Get predictions
        with torch.no_grad():
            predictions = model(**inputs).logits

            # Convert predictions to probabilities and get the highest probability class
            probabilities = torch.nn.functional.softmax(predictions, dim=-1)
            confidences, predicted_class_idx = torch.max(probabilities, dim=-1)
            predicted_class = class_labels[predicted_class_idx]#Something with +1 to shift the labels if we add a No Cat label
        print(probabilities)

        # Check if confidence is above the threshold
        if confidences.item() < confidence_threshold:
            label = 'No Cat'
            confidence = 0
        else:
            label = class_labels[predicted_class_idx.item()]  # +1 to account for 'No Cat'
            confidence = confidences.item()
            

        # Prepare the display text
        display_text = f'{label} ({confidence:.2f})'

        # Display the prediction on the frame
        cv2.putText(frame_resized, display_text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

        # Display the resulting frame
        cv2.imshow('Cat or Not', frame_resized)

        # Break the loop with 'q'
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

# Release the capture when done
cap.release()
cv2.destroyAllWindows()


tensor([[0.0604, 0.0444, 0.8952]])
tensor([[0.0200, 0.0209, 0.9591]])
tensor([[0.0189, 0.0185, 0.9626]])
tensor([[0.0185, 0.0181, 0.9634]])
tensor([[0.0189, 0.0182, 0.9629]])
tensor([[0.0193, 0.0186, 0.9621]])
tensor([[0.0194, 0.0187, 0.9619]])
tensor([[0.0193, 0.0184, 0.9622]])
tensor([[0.0192, 0.0181, 0.9626]])
tensor([[0.0192, 0.0180, 0.9628]])
tensor([[0.0190, 0.0178, 0.9632]])
tensor([[0.0184, 0.0176, 0.9639]])
tensor([[0.0182, 0.0177, 0.9641]])
tensor([[0.0186, 0.0174, 0.9640]])
tensor([[0.0188, 0.0174, 0.9638]])
tensor([[0.0186, 0.0173, 0.9641]])
tensor([[0.0185, 0.0172, 0.9643]])
tensor([[0.0198, 0.0184, 0.9618]])
tensor([[0.0196, 0.0178, 0.9626]])
tensor([[0.0195, 0.0177, 0.9628]])
tensor([[0.0197, 0.0176, 0.9627]])
tensor([[0.0196, 0.0174, 0.9630]])
tensor([[0.0194, 0.0172, 0.9634]])
tensor([[0.0193, 0.0177, 0.9630]])
tensor([[0.0193, 0.0180, 0.9627]])
tensor([[0.0191, 0.0179, 0.9630]])
tensor([[0.0192, 0.0179, 0.9629]])
tensor([[0.0192, 0.0179, 0.9629]])
tensor([[0.0192, 0.0

## Video

In [11]:
import cv2

# Set up video capture device (webcam or external camera)
cap = cv2.VideoCapture(0)  # '0' is typically the default webcam

# Define the codec and create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
out = cv2.VideoWriter('temp_video/output.mp4', fourcc, 20.0, (width, height))

# Check if the camera opened successfully
if not cap.isOpened():
    print("Error: Could not open video device.")
else:
    print("Recording... Press 'q' to stop.")

# Capture and record video frames
frame_count = 0
while cap.isOpened():
    ret, frame = cap.read()
    if ret:
        frame_count += 1
        out.write(frame)
        cv2.imshow('Recording', frame)

        # Press 'q' to stop recording
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

# Release the capture and writer objects
cap.release()
out.release()

# Close all OpenCV windows
cv2.destroyAllWindows()

# Check the output file size
import os
print(f"File size: {os.path.getsize('output.mp4')} bytes")


Recording... Press 'q' to stop.
File size: 1801315 bytes
