In [1]:
import cv2
import torch
from transformers import ViTImageProcessor, ViTForImageClassification

# Initialize the image processor and model
processor = ViTImageProcessor.from_pretrained('google/vit-base-patch16-224-in21k')
model = ViTForImageClassification.from_pretrained('ChrisGuarino/model')  # Replace with your model
model.eval()

# Define your class labels
class_labels = ['Prim', 'Rupe', 'No Cat']  # Replace with your actual labels

# Start the webcam
cap = cv2.VideoCapture(0)

#Confidence Threshold
confidence_threshold = .8  # Define a threshold

while True:
    ret, frame = cap.read()

    if ret:
        # Preprocess the frame
        frame_resized = cv2.resize(frame, (400, 400))
        frame_rgb = cv2.cvtColor(frame_resized, cv2.COLOR_BGR2RGB)
        inputs = processor(images=frame_rgb, return_tensors="pt")

        # Get predicti?ons
        with torch.no_grad():
            predictions = model(**inputs).logits

            # Convert predictions to probabilities and get the highest probability class
            probabilities = torch.nn.functional.softmax(predictions, dim=-1)
            confidences, predicted_class_idx = torch.max(probabilities, dim=-1)
            predicted_class = class_labels[predicted_class_idx]#Something with +1 to shift the labels if we add a No Cat label
        print(probabilities)

        # Check if confidence is above the threshold
        if confidences.item() < confidence_threshold:
            label = 'No Cat'
            confidence = 0
        else:
            label = class_labels[predicted_class_idx.item()]  # +1 to account for 'No Cat'
            confidence = confidences.item()

        # Prepare the display text
        display_text = f'{label} ({confidence:.2f})'

        # Display the prediction on the frame
        cv2.putText(frame_resized, display_text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

        # Display the resulting frame
        cv2.imshow('Cat or Not', frame_resized)

        # Break the loop with 'q'
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

# Release the capture when done
cap.release()
cv2.destroyAllWindows()


/Users/chrisguarino/opt/anaconda3/envs/yumyums_env3.9/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2024-08-07 10:04:31.729 python[37882:15440486] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.


tensor([[0.0227, 0.0190, 0.9584]])
tensor([[0.0188, 0.0165, 0.9647]])
tensor([[0.0193, 0.0160, 0.9647]])
tensor([[0.0177, 0.0160, 0.9663]])
tensor([[0.0180, 0.0158, 0.9662]])
tensor([[0.0175, 0.0153, 0.9672]])
tensor([[0.0177, 0.0156, 0.9667]])
tensor([[0.0186, 0.0165, 0.9649]])
tensor([[0.0170, 0.0161, 0.9668]])
tensor([[0.0170, 0.0161, 0.9669]])
tensor([[0.0162, 0.0154, 0.9684]])
tensor([[0.0168, 0.0164, 0.9668]])
tensor([[0.0167, 0.0152, 0.9681]])
tensor([[0.0150, 0.0143, 0.9707]])
tensor([[0.0149, 0.0144, 0.9708]])
tensor([[0.0154, 0.0138, 0.9708]])
tensor([[0.0151, 0.0140, 0.9709]])
tensor([[0.0153, 0.0142, 0.9705]])
tensor([[0.0154, 0.0142, 0.9704]])
tensor([[0.0152, 0.0140, 0.9708]])
tensor([[0.0149, 0.0138, 0.9713]])
tensor([[0.0149, 0.0141, 0.9710]])
tensor([[0.0150, 0.0138, 0.9712]])
tensor([[0.0151, 0.0142, 0.9707]])
tensor([[0.0153, 0.0144, 0.9703]])
tensor([[0.0153, 0.0144, 0.9704]])
tensor([[0.0154, 0.0142, 0.9704]])
tensor([[0.0157, 0.0143, 0.9700]])
tensor([[0.0159, 0.0